app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('tambah-item/', views.tambah_item, name='tambah-item'),
    path('update-item/', views.update_item, name='update-item'),
    path('daftar-item/', views.daftar_item, name='daftar-item'),
    path('delete-item/', views.delete_item, name='delete-item'),
    path('profil/', views.profil, name='profil'),
    path('chat/', views.chat, name='chat'),
    path('add-goods/', views.add_goods, name='add-goods'),
    path('add-goods/<str:nama_item>/', views.add_goods_slug, name='add-goods-slug'),
    path('update-goods/<str:id_barang>', views.update_goods, name='update-goods'),
    path('view-goods/', views.view_goods, name='view-goods'),
    path('view-goods/<str:nama_item>/', views.view_goods_slug, name='view-goods-slug'),
    path('view-goods-details/<str:id_barang>', views.view_goods_details, name='view-goods-details'),
    path('delete-goods/<str:id_barang>', views.delete_goods, name='delete-goods'),
    path('view-form-pesanan/', views.form_pemesanan, name='view-form-pesanan'),
    path('view-pesanan/', views.view_pemesanan, name='view-pesanan'),
    path('update-pesanan/<pesanan_slug>', views.update_pemesanan, name='update-pesanan'),
    path('view-level/', views.view_level, name='view-level'),
    path('form-level/', views.form_level, name='form-level'),
    path('update-level/<level_slug>', views.update_level, name='update-level'),
    path('view-review/', views.view_review, name='view-review'),
    path('view-pengiriman/', views.view_pengiriman, name='view-pengiriman'),
    path('form-review/', views.form_review, name='form-review'),
    path('update-review/', views.update_review, name='update-review'),
    path('view-form-pengiriman/', views.form_pengiriman, name='view-form-pengiriman'),
    path('get-item-info/', views.get_item_info, name='get-item-info'),
]

toys_rent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
]
static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/app/add-goods.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Tambah Barang{% endblock %}

{% block body %}
<div class="col-md-10 container">
    <div class="py-5 text-center">
        <h2>Form Penambahan Barang</h2>
    </div>
    <form action="{% url 'app:add-goods' %}" class="mx-5" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id-barang">ID barang</label>
            <input class="form-control" id="id-barang" name="id-barang" required type="text" />
        </div>
        <div class="mb-3">
            <label for="nama-item">Nama item</label>
            <select class="custom-select d-block w-100" id="nama-item" name="nama-item" required>
                <option value="">Pilih...</option>
                {% for item in items %}
                <option value="{{ item.nama }}">{{ item.nama }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="warna">Warna <span class="text-muted">(Opsional)</span></label>
            <input class="form-control" id="warna" name="warna" type="text" />
        </div>
        <div class="mb-3">
            <label for="url-foto">Url foto <span class="text-muted">(Opsional)</span></label>
            <input class="form-control" id="url-foto" name="url-foto" type="text" />
        </div>
        <div class="mb-3">
            <label for="kondisi">Kondisi</label>
            <input class="form-control" id="kondisi" name="kondisi" required type="text" />
        </div>
        <div class="mb-3">
            <label for="lama-penggunaan">Lama penggunaan <span class="text-muted">(Opsional)</span></label>
            <div class="input-group">
                <input class="form-control" id="lama-penggunaan" name="lama-penggunaan" type="month" />
                <div class="input-group-append">
                    <span class="input-group-text">Bulan</span>
                </div>
            </div>
        </div>
        <div class="mb-3">
            <label for="pemilik-penyewa">Pemilik/penyewa</label>
            <select class="custom-select d-block w-100" id="pemilik-penyewa" name="pemilik-penyewa" required>
                <option value="">Pilih...</option>
                {% for pemilik_penyewa in pemiliks_penyewas %}
                <option value="{{ pemilik_penyewa.no_ktp }}">{{ pemilik_penyewa.nama_lengkap }}</option>
                {% endfor %}
            </select>
        </div>
        <hr class="my-4" />
        <h4 class="mb-3">Info Barang</h4>
        <div class="mb-3">
            <h5>+ Bronze</h5>
            <div class="mb-3 row">
                <div class="col-md-6">
                    <label for="persen-royalty-bronze">Persen royalty</label>
                    <div class="input-group">
                        <input class="form-control" id="persen-royalty-bronze" name="persen-royalty-bronze" required type="number" />
                        <div class="input-group-append">
                            <span class="input-group-text">%</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="harga-sewa-bronze">Harga sewa</label>
                    <div class="input-group">
                        <input class="form-control" id="harga-sewa-bronze" name="harga-sewa-bronze" required type="number" />
                        <div class="input-group-append">
                            <span class="input-group-text">Rupiah/minggu</span>
                        </div>
                    </div>
                </div>
            </div>
            <h5>+ Silver</h5>
            <div class="mb-3 row">
                <div class="col-md-6">
                    <label for="persen-royalty-silver">Persen royalty</label>
                    <div class="input-group">
                        <input class="form-control" id="persen-royalty-silver" name="persen-royalty-silver" required type="number" />
                        <div class="input-group-append">
                            <span class="input-group-text">%</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="harga-sewa-silver">Harga sewa</label>
                    <div class="input-group">
                        <input class="form-control" id="harga-sewa-silver" name="harga-sewa-silver" required type="number" />
                        <div class="input-group-append">
                            <span class="input-group-text">Rupiah/minggu</span>
                        </div>
                    </div>
                </div>
            </div>
            <h5>+ Gold</h5>
            <div class="mb-3 row">
                <div class="col-md-6">
                    <label for="persen-royalty-gold">Persen royalty</label>
                    <div class="input-group">
                        <input class="form-control" id="persen-royalty-gold" name="persen-royalty-gold" required type="number" />
                        <div class="input-group-append">
                            <span class="input-group-text">%</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="harga-sewa-gold">Harga sewa</label>
                    <div class="input-group">
                        <input class="form-control" id="harga-sewa-gold" name="harga-sewa-gold" required type="number" />
                        <div class="input-group-append">
                            <span class="input-group-text">Rupiah/minggu</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="my-4" />
        <button class="btn btn-block btn-lg btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %} | Toys Rent</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block heading %}
        {% endblock heading %}
    </head>
    <body class="bg-light">
        {% include 'app/navbar.html' %}
        {% block body %}{% endblock %}
        {% include 'app/footer.html' %}
    </body>
</html>

app/templates/app/form-level.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Form Level{% endblock %}
{% block body %}
<div class="col-md-10 container">
    <div class="py-5 text-center">
        <h2>Form Level</h2>
        {% if err %}
        <h2>Opps try again</h2>
        <h2>{{ err }}</h2>
        {% endif %}
    </div>
    <form class="mx-5" method="post">
        <div class="mb-3">
            <label for="id-barang">Nama Level</label>
            <input class="form-control" id="nama_level" required type="text" value="Gold"/>
        </div>
        <div class="mb-3">
            <label for="warna">Minimum Poin <span class="text-muted"></span></label>
            <input class="form-control" id="minimum_poin" required type="text" value="500"/>
        </div>
        <div class="mb-3">
            <label for="url-foto">Deskripsi<span class="text-muted"></span></label>
            <input class="form-control" id="deskripsi" required type="text" value="Highest Level"/>
        </div>
        <hr class="my-4" />
        <button class="btn btn-block btn-lg btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/app/form-pemesanan.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Tambah Pesanan{% endblock %}
{% block heading %}
<script>
function showModal() {
    $("#confirmed").modal("show");
}
function createPesanan(ktp, barang, waktu, harga) {
    $.ajax(
        {
            url: "/view-form-pesanan/",
            data : {"no_ktp" : ktp, "barang" : barang, "waktu": waktu, "harga" : harga, "confirm": true, csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value },
            method : "POST",
        }
    )
}

</script>
{% endblock %}
{% block body %}
<div class="col-md-10 container">
    <div class="py-5 text-center">
        <h2>Form Pemesanan Barang</h2>
    </div>
    {% if total %}
  <div class="modal" id="confirmed">
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title"> Konfirmasi Pemesanan </h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body"> 
          The total price is {{total}}, do you wish to continue? {{anggota}}
        </div>

        <!-- Modal footer -->
        {% csrf_token %}
        <div class="modal-footer">
          <button id="del-but" type="button" class="btn btn-secondary" data-dismiss="modal">No, Dont</button>
          <button id="accept-but" type="button" class="btn btn-primary" data-dismiss="modal" onClick="createPesanan(`{{anggota}}`, {{list_barang}}, {{waktu}}, {{total}})">Yes, Continue</button>
        </div>

      </div>
    </div>
  </div>
  <script> showModal(); //alert("peepgagiga");</script>
  {% endif %}

    <form action="{% url 'app:view-form-pesanan' %}" class="mx-5" method="post">
    {% csrf_token %}
        <label>Anggota</label>
        {% if tipe_pengguna == 'admin' %}
        <div class="mb-3">
            <select class="custom-select d-block w-100" name="anggota" id="barang" required>
            {% for anggota in list_anggota %}
                <option type="radio" value="{{anggota.no_ktp}}">{{ anggota.no_ktp}}</option>
            {% endfor %}
            </select>
        </div>
        {% else %}
        <div class="mb-3">
            <input name="anggota" id="anggota" list="list_anggota" value="{{list_anggota}}" disabled>
        </div>
        {% endif %}
        <div class="mb-3">
            <label>List Barang</label>
            <select class="custom-select d-block w-100" name="barang" id="barang" required multiple>
                {% for barang in barang %}
                <option type="radio" value="{{ barang.id_barang }}">{{ barang.nama_item }}</option>
                {% endfor %}
            </select>
        </div>
        <hr class="my-4" />
        <div class="mb-3">
            <label for="lama-sewa">Lama Sewa<span class="text-muted"></span></label>
            <div class="input-group">
                <input class="form-control"name="waktu" id="waktu" type="text" />
                <div class="input-group-append">
                    <span class="input-group-text">Isi dengan integer (Hari)</span>
                </div>
            </div>
        </div>
        <button class="btn btn-block btn-lg btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/app/form-pengiriman.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Tambah Pengiriman{% endblock %}

{% block body %}
<div class="col-md-10 container">
    <div class="py-5 text-center">
        <h2>Form Pengiriman Barang</h2>
    </div>
    <form action="{% url 'app:view-form-pengiriman' %}" class="mx-5">
        {% if user == 'admin' %}<div class="mb-3">
            <label>Anggota / Admin</label>
            <select class="custom-select d-block w-100" id="nama-anggota" required>
                <option value="">Pilih...</option>
                {% for anggota in anggota %}
                <option value="{{ anggota }}">{{ anggota }}</option>
                {% endfor %}
            </select>
        </div>
        {% endif %}
        <div class="mb-3">
            <label>List Barang</label>
            <select class="custom-select d-block w-100" id="list-barang" required>
                <option type="radio" value="">Pilih...</option>
                {% for barang in barang %}
                <option type="radio" value="{{ barang }}">{{ barang }}</option>
                {% endfor %}
            </select>
        </div>
        <hr class="my-4" />
        <div class="mb-3">
            <label for="lama-sewa">Lama Sewa<span class="text-muted"></span></label>
            <div class="input-group">
                <input class="form-control" id="lama-sewa" type="date" />
                <div class="input-group-append">
                    <span class="input-group-text">Hari</span>
                </div>
            </div>
        </div>
        <button class="btn btn-block btn-lg btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/app/form-review.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Form Review Barang{% endblock %}

{% block body %}
<div class="col-md-10 container">
    <div class="py-5 text-center">
        <h2>Form Review Barang</h2>
    </div>
    <form class="mx-5">
        <div class="mb-3">
            <label for="id-barang">ID Barang</label>
            <input class="form-control" id="level" required type="text"></input>
        </div>
        <div class="mb-3">
            <label for="warna">Deskripsi<span class="text-muted"></span></label>
            <input class="form-control" id="poin" type="text"/>
        </div>
        <hr class="my-4" />
        <button class="btn btn-block btn-lg btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}
{% block body %} 
<div id="container" class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="display-4 text-center">Form Login</h1>
            <div class="info-form">
              <form action="{% url 'app:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group row">
                  <label for="no_ktp" class="col-2 col-form-label">Nomor Ktp</label>
                  <div class="col-10">
                    <input type="text" class="form-control" id="no_ktp" name="no_ktp"  placeholder="1090123xxx">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="email" class="col-2 col-form-label">Email</label>
                  <div class="col-10">
                    <input type="email" class="form-control" id="email" name="email" placeholder="toysrent@gmail.com">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Login</button>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-12 text-center">
                    <label style="color:red">{{error}}</label>
                  </div>
                </div>
              </form> 
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock body %} 

app/templates/app/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'app:index' %}">Toys Rent</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {% if request.session.is_anggota %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:profil' %}">Profil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:daftar-item' %}">Daftar Item</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:view-goods' %}">Daftar Barang</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Pesanan
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'app:view-form-pesanan' %}">Buat Pesanan</a>
                <a class="dropdown-item" href="{% url 'app:view-pesanan' %}">Daftar Pesanan</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Pengiriman
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'app:view-form-pengiriman' %}">Buat Pengiriman</a>
                <a class="dropdown-item" href="{% url 'app:view-pengiriman' %}">Daftar Pengiriman</a>
              </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:chat' %}">Chat dengan Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:view-review' %}">Daftar Review Barang</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a>
            </li>
            {% elif request.session.is_admin %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:profil' %}">Profil</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Item
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'app:tambah-item' %}">Tambah Item</a>
                <a class="dropdown-item" href="{% url 'app:daftar-item' %}">Daftar Item</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Barang
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'app:add-goods' %}">Tambah Barang</a>
                <a class="dropdown-item" href="{% url 'app:view-goods' %}">Daftar Barang</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Level
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'app:form-level' %}">Tambah Level</a>
                <a class="dropdown-item" href="{% url 'app:view-level' %}">Daftar Level</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Pesanan
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'app:view-form-pesanan' %}">Buat Pesanan</a>
                <a class="dropdown-item" href="{% url 'app:view-pesanan' %}">Daftar Pesanan</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Pengiriman
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'app:view-form-pengiriman' %}">Buat Pengiriman</a>
                <a class="dropdown-item" href="{% url 'app:view-pengiriman' %}">Daftar Pengiriman</a>
              </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:chat' %}">Chat dengan Pengguna</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:view-review' %}">Daftar Review Barang</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
            </li>
            {% else %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:signup' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                </li>
            </ul>
            {% endif %}
        </ul>
    </div>
</nav>

app/templates/app/update_item.html
{% extends "app/base.html" %}
{% load static %}

{% block heading %}
<script src="{% static 'js/update_item.js' %}"></script>
{% endblock %}

{% block body %} 
<div id="container" class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="display-4 text-center">Form Update Item</h1>
            <div class="info-form">
              <form id="update-item-form" action="{% url 'app:update-item' %}" method="POST">
                <meta name="csrf-token" content="{{ csrf_token }}">
                <div class="form-group row">
                  <label for="nama-item" class="col-2 col-form-label">Nama</label>
                  <div class="col-10">
                    <input type="text" class="form-control" id="nama-item" name="nama-item" required>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="deskripsi-item" class="col-2 col-form-label">Deskripsi</label>
                  <div class="col-10" required>
                    <input type="text" class="form-control" id="deskripsi-item" name="deskripsi-item">
                  </div>  
                </div>
                <div class="form-group row">
                  <label for="rentang-usia" class="col-2 col-form-label">Rentang Usia</label>
                  <div class="col-4" required>
                    <input type="number" class="form-control" id="usia-minimal" name="usia-minimal" placeholder="Usia minimal">
                  </div>
                  <div class="col-1 text-center">
                    <p> - </p>
                  </div>
                  <div class="col-4" required>
                    <input type="number" class="form-control" id="usia-maksimal" name="usia-maksimal" placeholder="Usia maksimal">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="bahan-item" class="col-2 col-form-label">Bahan</label>
                  <div class="col-10">
                    <input type="text" class="form-control" id="bahan-item"  name="bahan-item">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="col-2 col-form-label">Kategori</label>
                  <div class="col-10">
                    Gunakan ctrl + click (windows) atau command + click (mac) untuk memilih lebih dari satu kategori
                    <select multiple name="kategori-item" class="custom-select" id="kategori-item">
                      {% for i in kategori %}
                      <option>{{i}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </div>
                <div class="form-group row text-center">
                  <div class="col-12">
                    <label style="color:red" id="error-text">{{error}}</label>
                  </div>
                </div>
              </form> 
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock body %} 

app/templates/app/view-goods.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Tambah Barang{% endblock %}
{% block body %}
<div class="col-md-10 container">
    <div class="py-5 text-center">
        <h2>Daftar Barang</h2>
    </div>
    <form action="{% url 'app:view-goods' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="urutan">Urutkan berdasarkan:</label>
            <select class="custom-select d-block w-100" id="urutan" name="urutan" onchange="if(this.value != 0) { this.form.submit(); }">
                <option value="">Pilih...</option>
                <option value="nama">Nama</option>
                <option value="kategori">Kategori</option>
            </select>
        </div>
    </form>
    <form>
        <table class="table text-center">
            <thead>
                <tr>
                    <th scope="col">ID Barang</th>
                    <th scope="col">Nama Item</th>
                    <th scope="col">Warna</th>
                    <th scope="col">Kondisi</th>
                    <th scope="col">Action Semua User</th>
                    {% if user == 'admin' %}<th scope="col">Action Admin</th>{% endif %}
                    {% if user == 'anggota' %}<th scope="col">Action Anggota</th>{% endif %}
                </tr>
            </thead>
            <tbody>
                {% for good in goods %}
                <tr>
                    <td>{{ good.id_barang }}</td>
                    <td>{{ good.nama_item }}</td>
                    <td>{{ good.warna }}</td>
                    <td>{{ good.kondisi }}</td>
                    <td><a href="/view-goods-details/{{ good.id_barang }}" class="btn btn-primary">Lihat Detail Barang</a></td>
                    {% if user == 'admin' %}
                    <td>
                        <a href="/update-goods/{{ good.id_barang }}" class="btn btn-primary">Update</a>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#id{{ good.id_barang }}">
                            Delete
                        </button>
                        <div class="modal fade" id="id{{ good.id_barang }}" tabindex="-1" role="dialog" aria-labelledby="{{ good.id_barang }}Title" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">ID Barang: {{ good.id_barang }}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Apakah kamu yakin ingin menghapus barang ini?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary" data-dismiss="modal">Tidak</button>
                                        <button onclick="location.href='/delete-goods/{{ good.id_barang }}'" type="button" class="btn btn-danger">Ya</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    {% endif %}
                    {% if user == 'anggota' %}
                    <td>
                        <div class="custom-control custom-checkbox">
                        <input class="custom-control-input" id="{{ good.id_barang }}" type="checkbox" />
                        <label class="custom-control-label" for="{{ good.id_barang }}"></label>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if user == 'anggota' %}
        <hr class="my-4" />
        <button class="btn btn-block btn-lg btn-primary" type="submit">Pesan</button>
        {% endif %}
    </form>
</div>
{% endblock %}